In [1]:
import pandas as pd
from collections import defaultdict
import re
import yaml

In [2]:
%run -i "comment.py"
%run -i "indicator.py"
%run -i "objects.py"
%run -i "periods.py"
%run -i "section.py"

In [3]:
yaml_file = open('regions_etalon.yaml', 'r', encoding="utf8")

In [14]:
sect_5 = Section(source = 'Раздел 5 - Здравоохранение.xlsx', regions_dict = 'regions_etalon.yaml')

In [15]:
for sh in sect_5.sheet_names():

    print(sh)
    df = pd.DataFrame(sect_5.process_sheet(sh))
    print("Comment: "+ df.loc[2, 'comment'])
    display(df.sample(1))

5.1.1
Section is:  Здравоохранение  Indicator is:  Число больничных коек: Всего  Unit is:  на конец года, тысяч коек
Comment: 1) ЧИСЛО БОЛЬНИЧНЫХ КОЕК: 2005 г. – включая койки дневных стационаров.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1211,Здравоохранение,Число больничных коек: Всего,"на конец года, тысяч коек",05010100,Удмуртская Республика,регион,94000000,94000000,2001,21.1,1) ЧИСЛО БОЛЬНИЧНЫХ КОЕК: 2005 г. – включая ко...,No subsection

5.1.2.
Section is:  Здравоохранение  Indicator is:  Число больничных коек: На 10 000 человек населения  Unit is:  на конец года, коек
Comment: 1) ЧИСЛО БОЛЬНИЧНЫХ КОЕК: 2005 г. – включая койки дневных стационаров. 2) : 2005 г. – включая койки дневных стационаров.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1449,Здравоохранение,Число больничных коек: На 10 000 человек насел...,"на конец года, коек",05010200,Уральский федеральный округ,федеральный округ,00000000,00000000,2019,78.0,1) ЧИСЛО БОЛЬНИЧНЫХ КОЕК: 2005 г. – включая ко...,No subsection

5.2.
Section is:  Здравоохранение  Indicator is:  Численность населения на одну больничную койку  Unit is:  на конец года, человек
Comment: 1) ЧИСЛЕННОСТЬ НАСЕЛЕНИЯ НА ОДНУ БОЛЬНИЧНУЮ КОЙКУ: 2005 г. – включая койки дневных стационаров.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1521,Здравоохранение,Численность населения на одну больничную койку,"на конец года, человек",05020000,Ханты-Мансийский автономный округ – Югра,регион,71800000,71100000,2003,102.4847,1) ЧИСЛЕННОСТЬ НАСЕЛЕНИЯ НА ОДНУ БОЛЬНИЧНУЮ КО...,No subsection

5.3.1.
Section is:  Здравоохранение  Indicator is:  Мощность амбулаторно-поликлинических организаций: . всего  Unit is:  на конец года, тысяч посещений в смену
Comment:

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
687,Здравоохранение,Мощность амбулаторно-поликлинических организац...,"на конец года, тысяч посещений в смену",05030100,Псковская область,регион,58000000,58000000,2005,17.4,,No subsection

5.3.2.
Section is:  Здравоохранение  Indicator is:  Мощность амбулаторно-поликлинических организаций: На 10 000 человек населения  Unit is:  на конец года, посещений в смену
Comment:

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1752,Здравоохранение,Мощность амбулаторно-поликлинических организац...,"на конец года, посещений в смену",05030200,Иркутская область,регион,25000000,25000000,2014,283.9,,No subsection

5.4.1.
Section is:  Здравоохранение  Indicator is:  Численность врачей всех специальностей: Всего  Unit is:  тысяч человек
Comment: 1) ЧИСЛЕННОСТЬ ВРАЧЕЙ ВСЕХ СПЕЦИАЛЬНОСТЕЙ: С 2012, 2015 гг. – изменение методологии сбора данных Минздравом России.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
692,Здравоохранение,Численность врачей всех специальностей: Всего,тысяч человек,05040100,Псковская область,регион,58000000,58000000,2010,2.3,1) ЧИСЛЕННОСТЬ ВРАЧЕЙ ВСЕХ СПЕЦИАЛЬНОСТЕЙ: С 2...,No subsection

5.4.2.
Section is:  Здравоохранение  Indicator is:  Численность врачей всех специальностей: На 10 000 человек населения  Unit is:  человек
Comment: 1) ЧИСЛЕННОСТЬ ВРАЧЕЙ ВСЕХ СПЕЦИАЛЬНОСТЕЙ: С 2012, 2015 гг. – изменение методологии сбора данных Минздравом России.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1674,Здравоохранение,Численность врачей всех специальностей: На 10 ...,человек,05040200,Республика Хакасия,регион,95000000,95000000,2002,36.9,1) ЧИСЛЕННОСТЬ ВРАЧЕЙ ВСЕХ СПЕЦИАЛЬНОСТЕЙ: С 2...,No subsection

5.5.1.
Section is:  Здравоохранение  Indicator is:  Нагрузка на работников сферы здравоохранения: Численность населения на одного врача  Unit is:  на конец года, человек
Comment: 1) Численность населения на одного врача, С 2012, 2015 гг. – изменение методологии сбора данных Минздравом России: С 2012, 2015 гг. – изменение методологии сбора данных Минздравом России.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
122,Здравоохранение,Нагрузка на работников сферы здравоохранения: ...,"на конец года, человек",05050100,Воронежская область,регион,20000000,20000000,2012,184.0,"1) Численность населения на одного врача, С 20...",203.8

5.5.2.
Section is:  Здравоохранение  Indicator is:  Нагрузка на работников сферы здравоохранения: Численность населения на одного работника среднего медицинского персонала  Unit is:  на конец года, человек
Comment: 1) Численность населения на одного работника среднего медицинского персонала: С 2012, 2015 гг. – изменение методологии сбора данных Минздравом России.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1503,Здравоохранение,Нагрузка на работников сферы здравоохранения: ...,"на конец года, человек",05050200,Тюменская область,регион,71000000,71000000,2007,77.0,1) Численность населения на одного работника с...,No subsection

5.6.1.
Section is:  Здравоохранение  Indicator is:  Численность среднего медицинского персонала: Всего  Unit is:  на конец года, тысяч человек
Comment:

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
412,Здравоохранение,Численность среднего медицинского персонала: В...,"на конец года, тысяч человек",05060100,Ярославская область,регион,78000000,78000000,2016,13.4,,No subsection

5.6.2.
Section is:  Здравоохранение  Indicator is:  Численность среднего медицинского персонала: На 10 000 человек населения  Unit is:  на конец года, человек
Comment:

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1024,Здравоохранение,Численность среднего медицинского персонала: Н...,"на конец года, человек",05060200,Карачаево-Черкесская Республика,регион,91000000,91000000,2012,110.6,,No subsection

5.7.1.
Section is:  Здравоохранение  Indicator is:  Прерывание беременности (аборты)  Unit is:  5.7.1. На 1000 женщин 15 - 49 лет
Comment:

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
655,Здравоохранение,Прерывание беременности (аборты),5.7.1. На 1000 женщин 15 - 49 лет,05070000,Мурманская область,регион,47000000,47000000,2017,23.0,,No subsection

5.7.2
Section is:  Здравоохранение  Indicator is:  Прерывание беременности (аборты)  Unit is:  5.7.2. На 100 родов
Comment:

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
120,Здравоохранение,Прерывание беременности (аборты),5.7.2. На 100 родов,05070000,Воронежская область,регион,20000000,20000000,2010,63.0,,No subsection

5.8.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
400,Здравоохранение,Заболеваемость на 1000 человек населения,зарегистрировано заболеваний у пациентов с диа...,05080000,Ярославская область,регион,78000000,78000000,2004,941.5,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения: Д...,No subsection

5.9.1.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Некоторые инфекционные и паразитарные болезни  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
800,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090100,Республика Крым,регион,35000000,35000000,2008,-99999999.0,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.2.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Новообразования  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
482,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090200,Республика Карелия,регион,86000000,86000000,2020,14.5,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.3.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни крови, кроветворных органов и отдельные нарушения, вовлекающие иммунный механизм  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
642,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090300,Мурманская область,регион,47000000,47000000,2004,3.3,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.4.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни эндокринной системы, расстройства питания и нарушения обмена веществ  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1405,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090400,Саратовская область,регион,63000000,63000000,2019,13.5,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.5.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни нервной системы  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
941,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090500,Северо-Кавказский федеральный округ,федеральный округ,00000000,00000000,2017,19.4,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.6.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни глаза и его придаточного аппарата  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1325,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090600,Оренбургская область,регион,53000000,53000000,2005,49.2,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.7.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни уха и сосцевидного отростка  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
668,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090700,Новгородская область,регион,49000000,49000000,2008,21.1,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.8.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни системы кровообращения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1684,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090800,Республика Хакасия,регион,95000000,95000000,2012,22.2,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.9.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни органов дыхания  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
726,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05090900,Южный федеральный округ,федеральный округ,00000000,00000000,2000,-99999999.0,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.10.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни органов пищеварения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
753,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091000,Республика Адыгея,регион,79000000,79000000,2005,21.8,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.11.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни кожи и подкожной клетчатки  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
782,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091100,Республика Калмыкия,регион,85000000,85000000,2012,45.7,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.12.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни костно-мышечной системы и соединительной ткани  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
2034,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091200,Магаданская область,регион,44000000,44000000,2010,27.0,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.13.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни мочеполовой системы  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
105,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091300,Владимирская область,регион,17000000,17000000,2017,44.8,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.14.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Врожденные аномалии (пороки развития), деформации и хромосомные нарушения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
610,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091400,Калининградская область,регион,27000000,27000000,2016,3.9,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.15.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Травмы, отравления и некоторые другие последствия воздействия внешних причин  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России. 2) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: Данные за 2000 - 2003 гг. в разрезе субъектов Российской Федерации отсутствуют.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
1223,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091500,Удмуртская Республика,регион,94000000,94000000,2013,115.9,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

5.9.16.
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Covid-19  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Comment: 1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО ОСНОВНЫМ КЛАССАМ БОЛЕЗНЕЙ: По данным Минздрава России.

,section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,subsection
162,Здравоохранение,Заболеваемость на 1000 человек населения по ос...,зарегистрировано заболеваний у пациентов с диа...,05091600,Калужская область,регион,29000000,29000000,2008,-99999999.0,1) ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ПО...,No subsection

In [16]:
sect_5.process_section().to_csv('section_5.csv')

Parse list  5.1.1  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Число больничных коек: Всего  Unit is:  на конец года, тысяч коек
Parse list  5.1.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Число больничных коек: На 10 000 человек населения  Unit is:  на конец года, коек
Parse list  5.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Численность населения на одну больничную койку  Unit is:  на конец года, человек
Parse list  5.3.1.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Мощность амбулаторно-поликлинических организаций: . всего  Unit is:  на конец года, тысяч посещений в смену
Parse list  5.3.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Мощность амбулаторно-поликлинических организаций: На 10 000 человек населения  Unit is:  на конец года, посещений в смену
Parse list  5.4.1.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Численность врачей всех специальностей: Всего  Unit is:  тысяч человек
Parse list  5.4.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Численность врачей всех специальностей: На 10 000 человек населения  Unit is:  человек
Parse list  5.5.1.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Нагрузка на работников сферы здравоохранения: Численность населения на одного врача  Unit is:  на конец года, человек
Parse list  5.5.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Нагрузка на работников сферы здравоохранения: Численность населения на одного работника среднего медицинского персонала  Unit is:  на конец года, человек
Parse list  5.6.1.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Численность среднего медицинского персонала: Всего  Unit is:  на конец года, тысяч человек
Parse list  5.6.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Численность среднего медицинского персонала: На 10 000 человек населения  Unit is:  на конец года, человек
Parse list  5.7.1.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Прерывание беременности (аборты)  Unit is:  5.7.1. На 1000 женщин 15 - 49 лет
Parse list  5.7.2  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Прерывание беременности (аборты)  Unit is:  5.7.2. На 100 родов
Parse list  5.8.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.1.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Некоторые инфекционные и паразитарные болезни  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.2.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Новообразования  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.3.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни крови, кроветворных органов и отдельные нарушения, вовлекающие иммунный механизм  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.4.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни эндокринной системы, расстройства питания и нарушения обмена веществ  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.5.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни нервной системы  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.6.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни глаза и его придаточного аппарата  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.7.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни уха и сосцевидного отростка  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.8.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни системы кровообращения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.9.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни органов дыхания  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.10.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни органов пищеварения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.11.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни кожи и подкожной клетчатки  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.12.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни костно-мышечной системы и соединительной ткани  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.13.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Болезни мочеполовой системы  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.14.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Врожденные аномалии (пороки развития), деформации и хромосомные нарушения  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.15.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Травмы, отравления и некоторые другие последствия воздействия внешних причин  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни
Parse list  5.9.16.  of file  Раздел 5 - Здравоохранение.xlsx
Section is:  Здравоохранение  Indicator is:  Заболеваемость на 1000 человек населения по основным классам болезней: Covid-19  Unit is:  зарегистрировано заболеваний у пациентов с диагнозом, установленным впервые в жизни